spring:
  profiles:
    active: default

---
server:
  port: 8082
spring:
  profiles: default
  redis:
    host: localhost
    port: 6379
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: testAdmin
    password: testPassword
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
  devtools:
    livereload:
      enabled: true

logging:
  level:
    org :
      springframework :
        security : info , debug
    com:
      web:
        toy : DEBUG


---
server:
  port: 8080
spring:
  profiles: production
  redis:
    host: localhost
    port: 6379
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: testAdmin
    password: testPassword
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
  devtools:
    livereload:
      enabled: true

logging:
  level:
    com:
      web:
        toy : info
