
profiles: local
server:
  port: 8082
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: testAdmin
    password: testPassword
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
  devtools:
    livereload:
      enabled: true

logging:
  level:
    com:
      web:
        toy : info
